services:
  api:
    build:
      context: ./api
    container_name: api_service
    ports:
      - "8000:8000"
    env_file:
      - .env

  web:
    build:
      context: ./web
    container_name: web_service
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api